import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { Text } from '@react-three/drei'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import * as THREE from 'three'
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js'
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js'
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass.js'
import './index.css'

type Result = 'HEADS' | 'TAILS' | null
const BASE_SPEED=2,DURATION=2.8,START_Y=4.5,CENTER_Y=0,COIN_RADIUS=1,COIN_THICKNESS=.24,COIN_SIDES=7
const HEPTAGON_ROTATION=Math.PI/2
const clamp01=(v:number)=>Math.max(0,Math.min(1,v)),easeOutCubic=(v:number)=>1-Math.pow(1-v,3)

function createSoftPolygon(radius:number,depth:number){const shape=new THREE.Shape(),start=-Math.PI/2;const cornerRadius=.105;const points:Array<[number,number]>=Array.from({length:COIN_SIDES},(_,i)=>{const a=start+i/COIN_SIDES*Math.PI*2;return [Math.cos(a)*radius,Math.sin(a)*radius]});for(let i=0;i<COIN_SIDES;i++){const [x,y]=points[i],[px,py]=points[(i+COIN_SIDES-1)%COIN_SIDES],[nx,ny]=points[(i+1)%COIN_SIDES];const lp=Math.hypot(px-x,py-y),ln=Math.hypot(nx-x,ny-y),t=Math.min(cornerRadius,lp*.28,ln*.28),a1=[x+(px-x)*t/lp,y+(py-y)*t/lp],a2=[x+(nx-x)*t/ln,y+(ny-y)*t/ln];if(i===0)shape.moveTo(a1[0],a1[1]);else shape.lineTo(a1[0],a1[1]);shape.quadraticCurveTo(x,y,a2[0],a2[1])}shape.closePath();const g=new THREE.ExtrudeGeometry(shape,{depth,steps:1,bevelEnabled:true,bevelThickness:.045,bevelSize:.14,bevelSegments:12,curveSegments:8});g.translate(0,0,-depth/2);return g}
function createCrownGeometry(){const s=new THREE.Shape();s.moveTo(-.34,-.18);s.lineTo(-.29,.18);s.lineTo(-.11,.02);s.lineTo(0,.24);s.lineTo(.11,.02);s.lineTo(.29,.18);s.lineTo(.34,-.18);s.lineTo(.22,-.28);s.lineTo(-.22,-.28);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:.045,bevelEnabled:true,bevelThickness:.018,bevelSize:.016,bevelSegments:3});g.translate(0,0,-.0225);return g}

function Face({type}:{type:'HEADS'|'TAILS'}){const isHeads=type==='HEADS',faceGeometry=useMemo(()=>createSoftPolygon(.87,.035),[]),crownGeometry=useMemo(()=>createCrownGeometry(),[]),z=isHeads?COIN_THICKNESS/2+.008:-COIN_THICKNESS/2-.008,detailZ=isHeads?.080:-.080;useEffect(()=>()=>{faceGeometry.dispose();crownGeometry.dispose()},[faceGeometry,crownGeometry]);const sideOffset=(v:number)=>isHeads?v:-v;return <group position={[0,0,z]}>
<mesh geometry={faceGeometry}><meshStandardMaterial color={isHeads?'#e7b84e':'#c8942d'} metalness={.97} roughness={.16} side={THREE.DoubleSide}/></mesh>
<mesh position={[0,0,sideOffset(.035)]} rotation={[0,0,HEPTAGON_ROTATION]}><ringGeometry args={[.695,.765,COIN_SIDES]}/><meshStandardMaterial color="#6e4510" metalness={.94} roughness={.2} side={THREE.DoubleSide}/></mesh>
<mesh position={[0,0,sideOffset(.041)]}><ringGeometry args={[.775,.825,COIN_SIDES]}/><meshStandardMaterial color="#f5ce67" metalness={.94} roughness={.14} side={THREE.DoubleSide}/></mesh>
<mesh position={[0,0,sideOffset(.045)]}><ringGeometry args={[.565,.59,64]}/><meshStandardMaterial color="#765016" metalness={.9} roughness={.18} side={THREE.DoubleSide}/></mesh>
<group position={[0,0,sideOffset(.052)]}>{'ONERING'.split('').map((letter,i)=>{const a=i/7*Math.PI*2-Math.PI/2;return <Text key={i} position={[Math.cos(a)*.675,Math.sin(a)*.675,0]} rotation={[0,0,a+Math.PI/2]} fontSize={.105} color="#51330b" anchorX="center" anchorY="middle" outlineWidth={.012} outlineColor="#d9a93e" material-side={THREE.DoubleSide}>{letter}</Text>})}</group>
{!isHeads&&<mesh position={[0,0,sideOffset(.055)]} rotation={[0,0,HEPTAGON_ROTATION+Math.PI]} scale={[1.5,1.5,1]}><torusGeometry args={[.34,.032,8,7]}/><meshStandardMaterial color="#f0c55c" metalness={.96} roughness={.14}/></mesh>}
{isHeads&&Array.from({length:COIN_SIDES}).map((_,i)=>{const a=i/COIN_SIDES*Math.PI*2+Math.PI/14;return <mesh key={i} position={[Math.cos(a)*.605,Math.sin(a)*.605,sideOffset(.058)]}><sphereGeometry args={[.028,10,8]}/><meshStandardMaterial color="#f4c85e" metalness={.98} roughness={.12}/></mesh>})}
{isHeads?<mesh geometry={crownGeometry} position={[0,0,detailZ]} rotation={[0,0,0]} scale={[1.18,1.18,1]}><meshStandardMaterial color="#b77a18" metalness={.92} roughness={.22} emissive="#6b3d08" emissiveIntensity={.22} side={THREE.DoubleSide}/></mesh>:<Text position={[0,0,-.095]} rotation={[0,0,Math.PI]} scale={[-1,1,1]} fontSize={.52} color="#4a2b05" anchorX="center" anchorY="middle" outlineWidth={.025} outlineColor="#f0c65b" material-side={THREE.DoubleSide}>50</Text>}
</group>}

function Coin({running,speed,result,onFinish}:{running:boolean;speed:number;result:Exclude<Result,null>|null;onFinish:(r:Exclude<Result,null>)=>void}){const group=useRef<THREE.Group>(null),rot=useRef<THREE.Group>(null),elapsed=useRef(0),was=useRef(false),finished=useRef(false),geom=useMemo(()=>createSoftPolygon(COIN_RADIUS,COIN_THICKNESS),[]);useEffect(()=>()=>geom.dispose(),[geom]);useEffect(()=>{if(running&&!was.current){elapsed.current=0;finished.current=false;was.current=true}if(!running)was.current=false},[running]);useFrame((_,d)=>{if(!group.current||!rot.current||!running||!result||finished.current)return;elapsed.current+=Math.min(d,.05)*speed;const p=clamp01(elapsed.current/DURATION);group.current.position.set(0,THREE.MathUtils.lerp(START_Y,CENTER_Y,easeOutCubic(p)),0);const target=result==='HEADS'?0:Math.PI;rot.current.rotation.set(target+(1-p)*Math.PI*10,0,0);if(p>=1){group.current.position.set(0,0,0);rot.current.rotation.set(target,0,0);finished.current=true;onFinish(result)}});return <group ref={group} position={[0,START_Y,0]}><group ref={rot}><mesh geometry={geom}><meshStandardMaterial color="#b47a1f" metalness={.98} roughness={.17}/></mesh><Face type="HEADS"/><Face type="TAILS"/></group></group>}

function Dust(){const ref=useRef<THREE.Points>(null);const positions=useMemo(()=>{const a=new Float32Array(90*3);for(let i=0;i<90;i++){a[i*3]=(Math.random()-.5)*9;a[i*3+1]=(Math.random()-.5)*7;a[i*3+2]=(Math.random()-.5)*2-2.5}return a},[]);useFrame((_,d)=>{if(ref.current){ref.current.rotation.y+=d*.008;ref.current.rotation.z+=d*.003}});return <points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" args={[positions,3]}/></bufferGeometry><pointsMaterial color="#c8a95b" size={.018} transparent opacity={.32} sizeAttenuation/></points>}

function SoftShadow({running,speed}:{running:boolean;speed:number}){const ref=useRef<THREE.Mesh>(null),elapsed=useRef(0),was=useRef(false);useEffect(()=>{if(running&&!was.current){elapsed.current=0;was.current=true}if(!running)was.current=false},[running]);useFrame((_,d)=>{if(!ref.current)return;if(running){elapsed.current+=Math.min(d,.05)*speed;const p=clamp01(elapsed.current/DURATION),closeness=easeOutCubic(p);const s=THREE.MathUtils.lerp(.18,.72,closeness);ref.current.scale.set(s,s*.38,1);(ref.current.material as THREE.MeshBasicMaterial).opacity=THREE.MathUtils.lerp(.05,.22,closeness)}else{ref.current.scale.set(.72,.27,1)}});return <mesh ref={ref} position={[0,-.02,-.65]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[1,64]}/><meshBasicMaterial color="#000000" transparent opacity={.08} depthWrite={false}/></mesh>}

function PostProcessing(){const {gl,scene,camera,size}=useThree();const composer=useMemo(()=>{const c=new EffectComposer(gl);c.addPass(new RenderPass(scene,camera));c.addPass(new UnrealBloomPass(new THREE.Vector2(size.width,size.height),.42,.7,.82));return c},[gl,scene,camera]);useEffect(()=>{composer.setSize(size.width,size.height);composer.setPixelRatio(gl.getPixelRatio());return()=>composer.dispose()},[composer,size.width,size.height,gl]);useFrame(()=>composer.render(),1);return null}

function Scene(p:{running:boolean;speed:number;result:Exclude<Result,null>|null;onFinish:(r:Exclude<Result,null>)=>void}){return <div className="scene-wrap"><Canvas camera={{position:[0,0,10],fov:35}} dpr={[1,2]}><color attach="background" args={['#050810']}/><ambientLight intensity={.42}/><directionalLight position={[3,5,8]} intensity={2.5}/><directionalLight position={[-4,1,4]} intensity={1.2}/><spotLight position={[0,2,5]} target-position={[0,0,0]} angle={.55} penumbra={.3} intensity={9} distance={14} castShadow/><spotLight position={[-4,-2.5,5]} target-position={[0,0,0]} angle={.65} penumbra={.4} intensity={7} distance={14} castShadow/><spotLight position={[4,-2.5,5]} target-position={[0,0,0]} angle={.65} penumbra={.4} intensity={7} distance={14} castShadow/><spotLight position={[-4,-5,5]} target-position={[0,0,0]} angle={.7} penumbra={.35} intensity={12} distance={14} castShadow/><spotLight position={[4,-5,5]} target-position={[0,0,0]} angle={.7} penumbra={.35} intensity={12} distance={14} castShadow/><pointLight position={[-2.8,1.5,-3.5]} color="#36d8ff" intensity={18} distance={8}/><pointLight position={[2.8,-1.5,-3.5]} color="#ffd06a" intensity={16} distance={8}/><Dust/><SoftShadow running={p.running} speed={p.speed}/><Coin {...p}/><PostProcessing/></Canvas><div className="vignette"/></div>}

function App(){const[running,setRunning]=useState(false),[speed,setSpeed]=useState(BASE_SPEED),[result,setResult]=useState<Result>(null),[flips,setFlips]=useState(0),flip=useCallback(()=>{if(running)return;setResult(Math.random()<.5?'HEADS':'TAILS');setRunning(true)},[running]),finish=useCallback((r:Exclude<Result,null>)=>{setResult(r);setFlips(n=>n+1);setRunning(false)},[]);useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.code==='Space'){e.preventDefault();flip()}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[flip]);return <main className="app-shell"><header className="topbar"><div><span className="eyebrow">THREE.JS COIN FLIP</span><h1>Coin Flip</h1></div><div className="stats"><span>FLIPS</span><strong>{flips}</strong></div></header><section className="game-card"><div className="viewport"><Scene running={running} speed={speed} result={result} onFinish={finish}/></div><div className="hud"><div className="result-box"><span>RESULT</span><strong>{result??(running?'FLIPPING…':'READY')}</strong></div><button className="flip-button" onClick={flip} disabled={running}>{running?'FLIPPING…':'FLIP COIN'}</button><div className="speed-control"><div className="speed-label"><span>ANIMATION SPEED</span><strong>{speed}×</strong></div><input aria-label="Animation speed" type="range" min="1" max="4" step="1" value={speed/BASE_SPEED} onChange={e=>setSpeed(Number(e.target.value)*BASE_SPEED)}/><div className="speed-ticks"><span>2× BASE</span><span>8× FAST</span></div></div></div></section><p className="hint">Press <kbd>SPACE</kbd> to flip</p></main>}
export default App
