import { Canvas, useFrame } from '@react-three/fiber'
import { Text } from '@react-three/drei'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import * as THREE from 'three'
import './index.css'

type Result = 'HEADS' | 'TAILS' | null
const BASE_SPEED=2,DURATION=2.8,START_Y=4.5,CENTER_Y=0,COIN_RADIUS=1,COIN_THICKNESS=.24,COIN_SIDES=7
const HEPTAGON_ROTATION=Math.PI/2
const clamp01=(v:number)=>Math.max(0,Math.min(1,v)),easeOutCubic=(v:number)=>1-Math.pow(1-v,3)
function createSoftPolygon(radius:number,depth:number){const shape=new THREE.Shape(),start=-Math.PI/2;for(let i=0;i<=COIN_SIDES;i++){const a=start+i/COIN_SIDES*Math.PI*2,x=Math.cos(a)*radius,y=Math.sin(a)*radius;if(i===0)shape.moveTo(x,y);else shape.lineTo(x,y)}const g=new THREE.ExtrudeGeometry(shape,{depth,steps:1,bevelEnabled:true,bevelThickness:.045,bevelSize:.14,bevelSegments:12,curveSegments:8});g.translate(0,0,-depth/2);return g}
function createCrownGeometry(){const s=new THREE.Shape();s.moveTo(-.34,-.18);s.lineTo(-.29,.18);s.lineTo(-.11,.02);s.lineTo(0,.24);s.lineTo(.11,.02);s.lineTo(.29,.18);s.lineTo(.34,-.18);s.lineTo(.22,-.28);s.lineTo(-.22,-.28);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:.045,bevelEnabled:true,bevelThickness:.018,bevelSize:.016,bevelSegments:3});g.translate(0,0,-.0225);return g}
function Face({type}:{type:'HEADS'|'TAILS'}){const isHeads=type==='HEADS',faceGeometry=useMemo(()=>createSoftPolygon(.87,.035),[]),crownGeometry=useMemo(()=>createCrownGeometry(),[]),z=isHeads?COIN_THICKNESS/2+.008:-COIN_THICKNESS/2-.008,detailZ=isHeads?.080:-.080;useEffect(()=>()=>{faceGeometry.dispose();crownGeometry.dispose()},[faceGeometry,crownGeometry]);const sideOffset=(v:number)=>isHeads?v:-v;return <group position={[0,0,z]}>
<mesh geometry={faceGeometry}><meshStandardMaterial color={isHeads?'#e7b84e':'#c8942d'} metalness={.97} roughness={.16} side={THREE.DoubleSide}/></mesh>
<mesh position={[0,0,sideOffset(.035)]} rotation={[0,0,HEPTAGON_ROTATION]}><ringGeometry args={[.695,.765,COIN_SIDES]}/><meshStandardMaterial color="#6e4510" metalness={.94} roughness={.2} side={THREE.DoubleSide}/></mesh>
<mesh position={[0,0,sideOffset(.041)]}><ringGeometry args={[.775,.825,COIN_SIDES]}/><meshStandardMaterial color="#f5ce67" metalness={.94} roughness={.14} side={THREE.DoubleSide}/></mesh>
<mesh position={[0,0,sideOffset(.045)]}><ringGeometry args={[.565,.59,64]}/><meshStandardMaterial color="#765016" metalness={.9} roughness={.18} side={THREE.DoubleSide}/></mesh>
<group position={[0,0,sideOffset(.052)]}>{'ONERING'.split('').map((letter,i)=>{const a=i/7*Math.PI*2-Math.PI/2;return <Text key={i} position={[Math.cos(a)*.675,Math.sin(a)*.675,0]} rotation={[0,0,a+Math.PI/2]} fontSize={.105} color="#51330b" anchorX="center" anchorY="middle" outlineWidth={.012} outlineColor="#d9a93e" material-side={THREE.DoubleSide}>{letter}</Text>})}</group>
{!isHeads&&<mesh position={[0,0,sideOffset(.055)]} rotation={[0,0,HEPTAGON_ROTATION+Math.PI]} scale={[1.5,1.5,1]}><torusGeometry args={[.34,.032,8,7]}/><meshStandardMaterial color="#f0c55c" metalness={.96} roughness={.14}/></mesh>}
{isHeads&&Array.from({length:COIN_SIDES}).map((_,i)=>{const a=i/COIN_SIDES*Math.PI*2+Math.PI/14;return <mesh key={i} position={[Math.cos(a)*.605,Math.sin(a)*.605,sideOffset(.058)]}><sphereGeometry args={[.028,10,8]}/><meshStandardMaterial color="#f4c85e" metalness={.98} roughness={.12}/></mesh>})}
{isHeads?<mesh geometry={crownGeometry} position={[0,0,detailZ]} rotation={[0,0,0]} scale={[1.18,1.18,1]}><meshStandardMaterial color="#b77a18" metalness={.92} roughness={.22} emissive="#6b3d08" emissiveIntensity={.22} side={THREE.DoubleSide}/></mesh>:<Text position={[0,0,-.095]} rotation={[0,0,Math.PI]} scale={[-1,1,1]} fontSize={.52} color="#4a2b05" anchorX="center" anchorY="middle" outlineWidth={.025} outlineColor="#f0c65b" material-side={THREE.DoubleSide}>50</Text>}
</group>}
function Coin({running,speed,result,onFinish}:{running:boolean;speed:number;result:Exclude<Result,null>|null;onFinish:(r:Exclude<Result,null>)=>void}){const group=useRef<THREE.Group>(null),rot=useRef<THREE.Group>(null),elapsed=useRef(0),was=useRef(false),finished=useRef(false),geom=useMemo(()=>createSoftPolygon(COIN_RADIUS,COIN_THICKNESS),[]);useEffect(()=>()=>geom.dispose(),[geom]);useEffect(()=>{if(running&&!was.current){elapsed.current=0;finished.current=false;was.current=true}if(!running)was.current=false},[running]);useFrame((_,d)=>{if(!group.current||!rot.current||!running||!result||finished.current)return;elapsed.current+=Math.min(d,.05)*speed;const p=clamp01(elapsed.current/DURATION);group.current.position.set(0,THREE.MathUtils.lerp(START_Y,CENTER_Y,easeOutCubic(p)),0);const target=result==='HEADS'?0:Math.PI;rot.current.rotation.set(target+(1-p)*Math.PI*10,0,0);if(p>=1){group.current.position.set(0,0,0);rot.current.rotation.set(target,0,0);finished.current=true;onFinish(result)}});return <group ref={group} position={[0,START_Y,0]}><group ref={rot}><mesh geometry={geom}><meshStandardMaterial color="#b47a1f" metalness={.98} roughness={.17}/></mesh><Face type="HEADS"/><Face type="TAILS"/></group></group>}
function Scene(p:{running:boolean;speed:number;result:Exclude<Result,null>|null;onFinish:(r:Exclude<Result,null>)=>void}){return <Canvas camera={{position:[0,0,10],fov:35}} dpr={[1,2]}><color attach="background" args={['#06080c']}/><ambientLight intensity={.55}/><directionalLight position={[3,5,8]} intensity={2.5}/><directionalLight position={[-4,1,4]} intensity={1.2}/><spotLight position={[0,2,5]} target-position={[0,0,0]} angle={.55} penumbra={.3} intensity={9} distance={14} castShadow/><spotLight position={[-4,-2.5,5]} target-position={[0,0,0]} angle={.65} penumbra={.4} intensity={7} distance={14} castShadow/><spotLight position={[4,-2.5,5]} target-position={[0,0,0]} angle={.65} penumbra={.4} intensity={7} distance={14} castShadow/><spotLight position={[-4,-5,5]} target-position={[0,0,0]} angle={.7} penumbra={.35} intensity={12} distance={14} castShadow/><spotLight position={[4,-5,5]} target-position={[0,0,0]} angle={.7} penumbra={.35} intensity={12} distance={14} castShadow/><Coin {...p}/></Canvas>}
function App(){const[running,setRunning]=useState(false),[speed,setSpeed]=useState(BASE_SPEED),[result,setResult]=useState<Result>(null),[flips,setFlips]=useState(0),flip=useCallback(()=>{if(running)return;setResult(Math.random()<.5?'HEADS':'TAILS');setRunning(true)},[running]),finish=useCallback((r:Exclude<Result,null>)=>{setResult(r);setFlips(n=>n+1);setRunning(false)},[]);useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.code==='Space'){e.preventDefault();flip()}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[flip]);return <main className="app-shell"><header className="topbar"><div><span className="eyebrow">THREE.JS COIN FLIP</span><h1>Coin Flip</h1></div><div className="stats"><span>FLIPS</span><strong>{flips}</strong></div></header><section className="game-card"><div className="viewport"><Scene running={running} speed={speed} result={result} onFinish={finish}/></div><div className="hud"><div className="result-box"><span>RESULT</span><strong>{result??(running?'FLIPPING…':'READY')}</strong></div><button className="flip-button" onClick={flip} disabled={running}>{running?'FLIPPING…':'FLIP COIN'}</button><div className="speed-control"><div className="speed-label"><span>ANIMATION SPEED</span><strong>{speed}×</strong></div><input aria-label="Animation speed" type="range" min="1" max="4" step="1" value={speed/BASE_SPEED} onChange={e=>setSpeed(Number(e.target.value)*BASE_SPEED)}/><div className="speed-ticks"><span>2× BASE</span><span>8× FAST</span></div></div></div></section><p className="hint">Press <kbd>SPACE</kbd> to flip</p></main>}export default App
